# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: web_sign

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
    # cron表达式，Actions时区是UTC时间，需要往前推8个小时  此时为6点30推送

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: kafan_sign
      env:
          KAFAN_SIGN: ${{ secrets.kafan_sign }}
      run: |
        python kafan_sign.py
    - name: right_sign
      env:
          RIGHT_SIGN: ${{ secrets.right_sign }}
      run: |
        python right_sign.py
    - name: v2ex_sign
      env:
          V2EX_SIGN: ${{ secrets.V2EX_sign }}
      run: |
        python v2ex_sign.py
